---
- name: add agent to k3s
  hosts: all
  become: True
  vars:
    api_endpoint: "{{ loadbalancer_ip }}"
    k3s_version: 'v1.25.11+k3s1'
    token: "{{ k3s_token }}"
    extra_agent_args: "{{ extra_agent_args }}"
  roles:
    - role: 'k3s_agent'
