---
- name: Set up k3s cluster
  hosts: all
  become: True
  vars:
    default_k3s_tls_san: ["127.0.0.1", "{{ loadbalancer_ip }}"]
    k3s_release_version: 'v1.18.19+k3s1'
    k3s_no_traefik: true
    k3s_no_coredns: true
    k3s_no_local_storage: true
    k3s_flannel_backend: "eth0"
    k3s_datastore_endpoint: postgres://{{ database_user }}:{{ database_password }}@{{ database_host }}:{{ database_port }}/{{ database_name }}
    k3s_control_node_address: "{{ loadbalancer_ip }}"
  pre_tasks:
    - name: Set each node to be a control node
      ansible.builtin.set_fact:
        k3s_node_ip_address: "{{ ansible_ssh_host }}"
        k3s_control_node: true
      when: inventory_hostname is startswith('prod-master-')
    - name: set tls san and ssh port
      ansible.builtin.set_fact: 
        k3s_tls_san: "{{ default_k3s_tls_san + master_ip_string.split(',') }}"
        ansible_port: 2222
  roles:
    - role: 'ansible-role-k3s'
