---
- name: Upload the k8s admin manifest to the remote host
  copy:
    src: "{{ playbook_dir }}/admin.yaml"
    dest: /tmp/admin.yaml
    mode: '0755'

- name: Execute the script on the remote host
  shell: kubectl apply -f /tmp/admin.yaml

- name: Upload the script to the remote host
  copy:
    src: "{{ playbook_dir }}/generate-config.sh"
    dest: /tmp/generate_output.sh
    mode: '0755'

- name: Execute the script on the remote host
  shell: /tmp/generate_output.sh > /tmp/config.yaml

- name: Fetch the generated file
  fetch:
    src: /tmp/config.yaml
    dest: "{{ playbook_dir }}/config.yaml"
    flat: yes

- name: get server token from remote
  shell: echo SERVER_TOKEN=`cat /var/lib/rancher/k3s/server/agent-token` > /tmp/token

- name: get k8s admin token from remote
  shell: echo K8S_ADMIN_TOKEN=`kubectl -n kube-system get secret $(kubectl -n kube-system get secret | grep admin-user | awk '{print $1}') -o jsonpath='{.data.token}' | base64 -d -w0` >> /tmp/token

- name: get k8s ca from remote
  shell: echo K8S_CA=`grep 'certificate-authority-data' /etc/rancher/k3s/k3s.yaml | awk '{ print $2 }'` >> /tmp/token

- name: Fetch server token file
  fetch:
    src: /tmp/token
    dest: "{{ playbook_dir }}/token.env"
    flat: yes
